import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

class IndexFrame:
    def __init__(self, top=None):
        top.geometry("992x628+294+117")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#9ae1d4")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.161, rely=0.828, height=101, width=644)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#9ae1d4")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe Print} -size 11 -slant italic")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="#000000")
        self.Label1.configure(text='''Humberto Alejandro Campos Torrejón    Adam Jhoel Mamani
  Yuri Daniel Ayaviri Quispe          Fabricio Alejandro Herrera Rojas
    Jim Gabriel Ariñez Bautista            Camila Belen Quispe Flores''')

        self.logoJhoelito = tk.Label(self.top)
        self.logoJhoelito.place(relx=0.06, rely=0.86, height=81, width=78)
        self.logoJhoelito.configure(activebackground="#d9d9d9")
        self.logoJhoelito.configure(activeforeground="black")
        self.logoJhoelito.configure(anchor='w')
        self.logoJhoelito.configure(background="#9ae1d4")
        self.logoJhoelito.configure(compound='left')
        self.logoJhoelito.configure(disabledforeground="#a3a3a3")
        self.logoJhoelito.configure(foreground="black")
        self.logoJhoelito.configure(highlightbackground="#d9d9d9")
        self.logoJhoelito.configure(highlightcolor="#000000")
        photo_location = os.path.join(_location,"./src/logoDimensionado.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.logoJhoelito.configure(image=_img0)

        self.logoSistemas = tk.Label(self.top)
        self.logoSistemas.place(relx=0.817, rely=0.828, height=111, width=110)
        self.logoSistemas.configure(activebackground="#d9d9d9")
        self.logoSistemas.configure(activeforeground="black")
        self.logoSistemas.configure(anchor='w')
        self.logoSistemas.configure(background="#9ae1d4")
        self.logoSistemas.configure(compound='left')
        self.logoSistemas.configure(disabledforeground="#a3a3a3")
        self.logoSistemas.configure(font="-family {Segoe UI} -size 9")
        self.logoSistemas.configure(foreground="black")
        self.logoSistemas.configure(highlightbackground="#d9d9d9")
        self.logoSistemas.configure(highlightcolor="#000000")
        photo_location = os.path.join(_location,"./src/logoSis.png")
        global _img1
        _img1 = tk.PhotoImage(file=photo_location)
        self.logoSistemas.configure(image=_img1)

        self.lblAnya = tk.Label(self.top)
        self.lblAnya.place(relx=-0.02, rely=0.334, height=241, width=256)
        self.lblAnya.configure(activebackground="#d9d9d9")
        self.lblAnya.configure(activeforeground="black")
        self.lblAnya.configure(anchor='w')
        self.lblAnya.configure(background="#9ae1d4")
        self.lblAnya.configure(compound='left')
        self.lblAnya.configure(disabledforeground="#a3a3a3")
        self.lblAnya.configure(foreground="#000000")
        self.lblAnya.configure(highlightbackground="#d9d9d9")
        self.lblAnya.configure(highlightcolor="#000000")
        photo_location = os.path.join(_location,"./src/imgAnya.png")
        global _img2
        _img2 = tk.PhotoImage(file=photo_location)
        self.lblAnya.configure(image=_img2)
        self.lblAnya.configure(text='''Label''')

        self.lblTresRaya = tk.Label(self.top)
        self.lblTresRaya.place(relx=0.202, rely=0.271, height=61, width=205)
        self.lblTresRaya.configure(activebackground="#d9d9d9")
        self.lblTresRaya.configure(activeforeground="black")
        self.lblTresRaya.configure(anchor='w')
        self.lblTresRaya.configure(background="#9ae1d4")
        self.lblTresRaya.configure(compound='left')
        self.lblTresRaya.configure(disabledforeground="#a3a3a3")
        self.lblTresRaya.configure(font="-family {Showcard Gothic} -size 21")
        self.lblTresRaya.configure(foreground="black")
        self.lblTresRaya.configure(highlightbackground="#d9d9d9")
        self.lblTresRaya.configure(highlightcolor="#000000")
        self.lblTresRaya.configure(text='''Tres en Raya''')

        self.lblTresRaya_1 = tk.Label(self.top)
        self.lblTresRaya_1.place(relx=0.353, rely=0.51, height=51, width=365)
        self.lblTresRaya_1.configure(activebackground="#d9d9d9")
        self.lblTresRaya_1.configure(activeforeground="black")
        self.lblTresRaya_1.configure(background="#9ae1d4")
        self.lblTresRaya_1.configure(compound='left')
        self.lblTresRaya_1.configure(disabledforeground="#a3a3a3")
        self.lblTresRaya_1.configure(font="-family {Showcard Gothic} -size 21")
        self.lblTresRaya_1.configure(foreground="black")
        self.lblTresRaya_1.configure(highlightbackground="#d9d9d9")
        self.lblTresRaya_1.configure(highlightcolor="#000000")
        self.lblTresRaya_1.configure(text='''Misioneros y Canibales''')

        self.lblTitle = tk.Label(self.top)
        self.lblTitle.place(relx=0.262, rely=0.032, height=50, width=548)
        self.lblTitle.configure(activebackground="#d9d9d9")
        self.lblTitle.configure(activeforeground="black")
        self.lblTitle.configure(anchor='w')
        self.lblTitle.configure(background="#9ae1d4")
        self.lblTitle.configure(compound='center')
        self.lblTitle.configure(cursor="fleur")
        self.lblTitle.configure(disabledforeground="#a3a3a3")
        self.lblTitle.configure(font="-family {Segoe Print} -size 30 -weight bold")
        self.lblTitle.configure(foreground="#000000")
        self.lblTitle.configure(highlightbackground="#d9d9d9")
        self.lblTitle.configure(highlightcolor="#000000")
        self.lblTitle.configure(text='''Práctica Primer Parcial''')

        self.lblSubtitle = tk.Label(self.top)
        self.lblSubtitle.place(relx=0.373, rely=0.111, height=39, width=292)
        self.lblSubtitle.configure(activebackground="#d9d9d9")
        self.lblSubtitle.configure(activeforeground="black")
        self.lblSubtitle.configure(anchor='w')
        self.lblSubtitle.configure(background="#9ae1d4")
        self.lblSubtitle.configure(compound='left')
        self.lblSubtitle.configure(disabledforeground="#a3a3a3")
        self.lblSubtitle.configure(font="-family {Segoe Print} -size 13")
        self.lblSubtitle.configure(foreground="#000000")
        self.lblSubtitle.configure(highlightbackground="#d9d9d9")
        self.lblSubtitle.configure(highlightcolor="#000000")
        self.lblSubtitle.configure(text='''Metodologías de Búsqueda''')

        self.lblChika = tk.Label(self.top)
        self.lblChika.place(relx=0.726, rely=0.271, height=281, width=266)
        self.lblChika.configure(activebackground="#d9d9d9")
        self.lblChika.configure(activeforeground="black")
        self.lblChika.configure(anchor='w')
        self.lblChika.configure(background="#9ae1d4")
        self.lblChika.configure(compound='left')
        self.lblChika.configure(cursor="fleur")
        self.lblChika.configure(disabledforeground="#a3a3a3")
        self.lblChika.configure(font="-family {Segoe UI} -size 9")
        self.lblChika.configure(foreground="#000000")
        self.lblChika.configure(highlightbackground="#d9d9d9")
        self.lblChika.configure(highlightcolor="#000000")
        photo_location = os.path.join(_location,"./src/imgChika.png")
        global _img3
        _img3 = tk.PhotoImage(file=photo_location)
        self.lblChika.configure(image=_img3)
        self.lblChika.configure(text='''Label''')

        self.btnG2 = tk.Button(self.top)
        self.btnG2.place(relx=0.565, rely=0.605, height=56, width=157)
        self.btnG2.configure(activebackground="#d9d9d9")
        self.btnG2.configure(activeforeground="black")
        self.btnG2.configure(background="#f9545b")
        self.btnG2.configure(disabledforeground="#a3a3a3")
        self.btnG2.configure(font="-family {Segoe Script} -size 15 -weight bold")
        self.btnG2.configure(foreground="#000000")
        self.btnG2.configure(highlightbackground="#d9d9d9")
        self.btnG2.configure(highlightcolor="#000000")
        self.btnG2.configure(text='''Grupo 2''')

        self.btnG1 = tk.Button(self.top)
        self.btnG1.place(relx=0.272, rely=0.382, height=56, width=157)
        self.btnG1.configure(activebackground="#d9d9d9")
        self.btnG1.configure(activeforeground="black")
        self.btnG1.configure(background="#ff9690")
        self.btnG1.configure(disabledforeground="#a3a3a3")
        self.btnG1.configure(font="-family {Segoe Script} -size 15 -weight bold")
        self.btnG1.configure(foreground="#000000")
        self.btnG1.configure(highlightbackground="#d9d9d9")
        self.btnG1.configure(highlightcolor="#000000")
        self.btnG1.configure(text='''Grupo 1''')

# Inicializacion de root.
root = tk.Tk()
root.protocol('WM_DELETE_WINDOW', root.destroy)
_top1 = root
_w1 = IndexFrame(_top1)

if __name__ == '__main__':
    root.mainloop()